=== Monash-Mosaic/IFRC_Report/scripts/wdr25/data/wdr25_from_styles.dtd
<!-- WDR25 DTD from styles (tiny v2.1, recursive) --><!-- Generated: 2025-10-08T15:25:01Z --><!ELEMENT Root (Story)><!ELEMENT Story ANY><!ELEMENT actor (#PCDATA)><!ELEMENT age-testimonials (#PCDATA)><!ELEMENT ambiguous (#PCDATA)><!ELEMENT answer (#PCDATA)><!ELEMENT bar (#PCDATA)><!ELEMENT bar-ex-afr (#PCDATA)><!ELEMENT bar-ex-am (#PCDATA)><!ELEMENT bar-explainer (#PCDATA)><!ELEMENT bibliography (#PCDATA)><!ELEMENT bibliography-first (#PCDATA)><!ELEMENT big-opening-quote-mark (#PCDATA)><!ELEMENT big-opening-quote-mark-yellow (#PCDATA)><!ELEMENT big-quote (#PCDATA)><!ELEMENT big-quote-author (#PCDATA)><!ELEMENT blueana ANY><!ELEMENT body-cell (#PCDATA)><!ELEMENT body-cell-core (#PCDATA)><!ELEMENT body-cell-core-last (#PCDATA)><!ELEMENT body-cell-core-next (#PCDATA)><!ELEMENT body-cell-fact (#PCDATA)><!ELEMENT body-fact (#PCDATA)><!ELEMENT body-left (#PCDATA)><!ELEMENT body-margin-box (#PCDATA)><!ELEMENT body-right (#PCDATA)><!ELEMENT bold (#PCDATA)><!ELEMENT bold-footer-small (#PCDATA)><!ELEMENT bold-italic (#PCDATA)><!ELEMENT bold-table (#PCDATA)><!ELEMENT book-subtitle (#PCDATA)><!ELEMENT book-title (#PCDATA)><!ELEMENT box-normal (#PCDATA)><!ELEMENT bullet-a (#PCDATA)><!ELEMENT bullet-body (#PCDATA)><!ELEMENT bullet-caption (#PCDATA)><!ELEMENT bullet-case-studies-icon (#PCDATA)><!ELEMENT bullet-ebn-icon (#PCDATA)><!ELEMENT bullet-ebn-icon-yellow (#PCDATA)><!ELEMENT bullet-list (#PCDATA)><!ELEMENT bullet-list-first (#PCDATA)><!ELEMENT bullet-q (#PCDATA)><!ELEMENT bullet-q-a-icon (#PCDATA)><!ELEMENT bullet-q6a-icon-alt-2 (#PCDATA)><!ELEMENT bullet-sublist (#PCDATA)><!ELEMENT caption (#PCDATA)><!ELEMENT caption-12c (#PCDATA)><!ELEMENT caption-2c (#PCDATA)><!ELEMENT caption-3c (#PCDATA)><!ELEMENT caption-4c (#PCDATA)><!ELEMENT caption-6c (#PCDATA)><!ELEMENT caption-anchor (#PCDATA)><!ELEMENT caption-anchor-core-chapter-image (#PCDATA)><!ELEMENT caption-box (#PCDATA)><!ELEMENT caption-chapter-core ANY><!ELEMENT caption-column ANY><!ELEMENT caption-contribution-images (#PCDATA)><!ELEMENT caption-margin ANY><!ELEMENT chapter-icon (#PCDATA)><!ELEMENT chapter-matrix (#PCDATA)><!ELEMENT chapter-number (#PCDATA)><!ELEMENT chapter-quote (#PCDATA)><!ELEMENT chapter-section (#PCDATA)><!ELEMENT chapter-title (#PCDATA)><!ELEMENT chapter-title-alt (#PCDATA)><!ELEMENT closing-quote-mark (#PCDATA)><!ELEMENT contact (#PCDATA)><!ELEMENT content-type (#PCDATA)><!ELEMENT content-type-cs (#PCDATA)><!ELEMENT content-type-insights (#PCDATA)><!ELEMENT content-type-q-a (#PCDATA)><!ELEMENT content-type-spotlight (#PCDATA)><!ELEMENT content-type-testimonials (#PCDATA)><!ELEMENT contribution-section-white (#PCDATA)><!ELEMENT contributor (#PCDATA)><!ELEMENT contributor-2c (#PCDATA)><!ELEMENT contributor-3c (#PCDATA)><!ELEMENT contributor-3c-first (#PCDATA)><!ELEMENT contributor-name-case-study (#PCDATA)><!ELEMENT contributor-name-ebn (#PCDATA)><!ELEMENT contributor-name-insights (#PCDATA)><!ELEMENT contributor-name-q-a (#PCDATA)><!ELEMENT contributor-name-spotlight (#PCDATA)><!ELEMENT contributor-name-testimonials (#PCDATA)><!ELEMENT contributor-name-vff (#PCDATA)><!ELEMENT contributor-position-case-study (#PCDATA)><!ELEMENT contributor-position-ebn (#PCDATA)><!ELEMENT contributor-position-insights (#PCDATA)><!ELEMENT contributor-position-q-a (#PCDATA)><!ELEMENT contributor-position-spotlight (#PCDATA)><!ELEMENT contributor-position-testimonials (#PCDATA)><!ELEMENT contributor-position-vff (#PCDATA)><!ELEMENT contributor-role (#PCDATA)><!ELEMENT contributor-role-2c (#PCDATA)><!ELEMENT contributor-role-3c (#PCDATA)><!ELEMENT core-chapter-tiktok-title ANY><!ELEMENT cover-blue ANY><!ELEMENT cover-red ANY><!ELEMENT credit-img (#PCDATA)><!ELEMENT cross-reference-link (#PCDATA)><!ELEMENT dimensions (#PCDATA)><!ELEMENT disclaimer ANY><!ELEMENT drop-cap-foreword (#PCDATA)><!ELEMENT dropcaps-bold-box-first (#PCDATA)><!ELEMENT dropcaps-box-first (#PCDATA)><!ELEMENT endnote (#PCDATA)><!ELEMENT fig ANY><!ELEMENT fig-num (#PCDATA)><!ELEMENT figure-description (#PCDATA)><!ELEMENT figure-description-white (#PCDATA)><!ELEMENT figure-description_numbered (#PCDATA)><!ELEMENT folio (#PCDATA)><!ELEMENT folio-white (#PCDATA)><!ELEMENT footer-cell (#PCDATA)><!ELEMENT footer-cell-core (#PCDATA)><!ELEMENT footer-col-cell-core (#PCDATA)><!ELEMENT footer-left (#PCDATA)><!ELEMENT footer-right (#PCDATA)><!ELEMENT footnote-number (#PCDATA)><!ELEMENT footnote-reference (#PCDATA)><!ELEMENT footnote-seperator (#PCDATA)><!ELEMENT footnotes (#PCDATA)><!ELEMENT footnotes-first (#PCDATA)><!ELEMENT footnotes-next (#PCDATA)><!ELEMENT foreword-body ANY><!ELEMENT guards-a-background ANY><!ELEMENT guards-b-background ANY><!ELEMENT guards-c-background ANY><!ELEMENT h.fig-number (#PCDATA)><!ELEMENT h0 (#PCDATA)><!ELEMENT h00 (#PCDATA)><!ELEMENT h1 (#PCDATA)><!ELEMENT h1-anx (#PCDATA)><!ELEMENT h1-anx-wide (#PCDATA)><!ELEMENT h1-bibliography (#PCDATA)><!ELEMENT h1-c1 (#PCDATA)><!ELEMENT h1-case-study (#PCDATA)><!ELEMENT h1-chapter-matrix (#PCDATA)><!ELEMENT h1-contributor (#PCDATA)><!ELEMENT h1-contributor-2c (#PCDATA)><!ELEMENT h1-contributor-3c (#PCDATA)><!ELEMENT h1-contributor-case-study (#PCDATA)><!ELEMENT h1-contributor-ebn (#PCDATA)><!ELEMENT h1-contributor-insights (#PCDATA)><!ELEMENT h1-contributor-q-a (#PCDATA)><!ELEMENT h1-contributor-spotlight (#PCDATA)><!ELEMENT h1-contributor-testimonials (#PCDATA)><!ELEMENT h1-contributor-vff (#PCDATA)><!ELEMENT h1-ebn (#PCDATA)><!ELEMENT h1-endnotes (#PCDATA)><!ELEMENT h1-example-matrix (#PCDATA)><!ELEMENT h1-first (#PCDATA)><!ELEMENT h1-harm (#PCDATA)><!ELEMENT h1-icon-topo (#PCDATA)><!ELEMENT h1-index (#PCDATA)><!ELEMENT h1-insights (#PCDATA)><!ELEMENT h1-next (#PCDATA)><!ELEMENT h1-number (#PCDATA)><!ELEMENT h1-principles (#PCDATA)><!ELEMENT h1-quote (#PCDATA)><!ELEMENT h1-sidenote-context (#PCDATA)><!ELEMENT h1-sidenotes-contributions (#PCDATA)><!ELEMENT h1-sidenotes-icon (#PCDATA)><!ELEMENT h1-spotlight (#PCDATA)><!ELEMENT h1-table (#PCDATA)><!ELEMENT h1-table-anx (#PCDATA)><!ELEMENT h1-testimonials (#PCDATA)><!ELEMENT h1-title-4l (#PCDATA)><!ELEMENT h1-title-5l (#PCDATA)><!ELEMENT h1-vff (#PCDATA)><!ELEMENT h1.1 (#PCDATA)><!ELEMENT h1.1-first (#PCDATA)><!ELEMENT h1.1-number (#PCDATA)><!ELEMENT h1.1.1 (#PCDATA)><!ELEMENT h1.1.1-number (#PCDATA)><!ELEMENT h1.1.1-restart (#PCDATA)><!ELEMENT h1.1.1.1 (#PCDATA)><!ELEMENT h1.1.1.1-number (#PCDATA)><!ELEMENT h1.1.1.1-restart (#PCDATA)><!ELEMENT h1.box (#PCDATA)><!ELEMENT h1.fig (#PCDATA)><!ELEMENT h1.fig-light (#PCDATA)><!ELEMENT h1.fig-light-next (#PCDATA)><!ELEMENT h1.fig-next (#PCDATA)><!ELEMENT h1.q-a (#PCDATA)><!ELEMENT h1.q-a-alt (#PCDATA)><!ELEMENT h1.q-a-alt-2 (#PCDATA)><!ELEMENT h1.q-a-alt-3 (#PCDATA)><!ELEMENT h1c2 (#PCDATA)><!ELEMENT h2 (#PCDATA)><!ELEMENT h2-case-study (#PCDATA)><!ELEMENT h2-case-study-numbered (#PCDATA)><!ELEMENT h2-case-study-numbered-first (#PCDATA)><!ELEMENT h2-ebn (#PCDATA)><!ELEMENT h2-insights (#PCDATA)><!ELEMENT h2-keep (#PCDATA)><!ELEMENT h2c1 (#PCDATA)><!ELEMENT h2c2 (#PCDATA)><!ELEMENT h3c2 (#PCDATA)><!ELEMENT hc (#PCDATA)><!ELEMENT header-background-purple ANY><!ELEMENT header-background-violet ANY><!ELEMENT header-background-yellow ANY><!ELEMENT header-cell (#PCDATA)><!ELEMENT header-left (#PCDATA)><!ELEMENT header-right (#PCDATA)><!ELEMENT header-txt ANY><!ELEMENT heading-1-box (#PCDATA)><!ELEMENT heading-3 (#PCDATA)><!ELEMENT heading-cell-core (#PCDATA)><!ELEMENT heading-celle-core-right (#PCDATA)><!ELEMENT hn (#PCDATA)><!ELEMENT hot-take (#PCDATA)><!ELEMENT humanity (#PCDATA)><!ELEMENT hyperlink (#PCDATA)><!ELEMENT hyperlink-email (#PCDATA)><!ELEMENT hyperlink-resources (#PCDATA)><!ELEMENT hyperlink-sources (#PCDATA)><!ELEMENT hyperlink-website (#PCDATA)><!ELEMENT hyperlinks-bio (#PCDATA)><!ELEMENT hyperlinks-italic-bio (#PCDATA)><!ELEMENT icon-contact (#PCDATA)><!ELEMENT icon-hot-take (#PCDATA)><!ELEMENT icon-photo (#PCDATA)><!ELEMENT icon-resources (#PCDATA)><!ELEMENT icon-website (#PCDATA)><!ELEMENT img-12c (#PCDATA)><!ELEMENT img-1c (#PCDATA)><!ELEMENT img-1c-next (#PCDATA)><!ELEMENT img-2c (#PCDATA)><!ELEMENT img-3c (#PCDATA)><!ELEMENT img-4c (#PCDATA)><!ELEMENT img-6c (#PCDATA)><!ELEMENT img-anchor ANY><!ELEMENT img-box (#PCDATA)><!ELEMENT img-chapter (#PCDATA)><!ELEMENT img-chapter-blue ANY><!ELEMENT img-chapter-contribution ANY><!ELEMENT img-chapter-core ANY><!ELEMENT img-chapter-core-full-frame ANY><!ELEMENT img-chapter-core-full-frame-blue ANY><!ELEMENT img-chapter-core-full-frame-red ANY><!ELEMENT img-chapter-red ANY><!ELEMENT img-column ANY><!ELEMENT img-margin ANY><!ELEMENT index-level-1 (#PCDATA)><!ELEMENT index-section-head (#PCDATA)><!ELEMENT intensional (#PCDATA)><!ELEMENT intent-ambiguous (#PCDATA)><!ELEMENT intent-intentional (#PCDATA)><!ELEMENT intent-unintentional (#PCDATA)><!ELEMENT intro (#PCDATA)><!ELEMENT intro-chapter ANY><!ELEMENT introduction (#PCDATA)><!ELEMENT italic-bio (#PCDATA)><!ELEMENT left-col-cell (#PCDATA)><!ELEMENT left-col-cell-core (#PCDATA)><!ELEMENT left-col-cell-core-last (#PCDATA)><!ELEMENT left-col-core (#PCDATA)><!ELEMENT letterhead (#PCDATA)><!ELEMENT light (#PCDATA)><!ELEMENT light-italic (#PCDATA)><!ELEMENT list-number-body (#PCDATA)><!ELEMENT list-number-sublist (#PCDATA)><!ELEMENT matrix (#PCDATA)><!ELEMENT matrix-big (#PCDATA)><!ELEMENT matrix-chapter-explainer ANY><!ELEMENT model (#PCDATA)><!ELEMENT navigation-link (#PCDATA)><!ELEMENT nb (#PCDATA)><!ELEMENT nonebreaking (#PCDATA)><!ELEMENT normal (#PCDATA)><!ELEMENT normal-2c (#PCDATA)><!ELEMENT normal-bullet-list (#PCDATA)><!ELEMENT normal-bullet-list-first (#PCDATA)><!ELEMENT normal-case-study (#PCDATA)><!ELEMENT normal-date (#PCDATA)><!ELEMENT normal-ebn (#PCDATA)><!ELEMENT normal-ebn-first (#PCDATA)><!ELEMENT normal-first (#PCDATA)><!ELEMENT normal-first-drop-cap (#PCDATA)><!ELEMENT normal-insights (#PCDATA)><!ELEMENT normal-lth (#PCDATA)><!ELEMENT normal-nested-bold (#PCDATA)><!ELEMENT normal-nxt (#PCDATA)><!ELEMENT normal-principles (#PCDATA)><!ELEMENT normal-psition (#PCDATA)><!ELEMENT normal-spotlight (#PCDATA)><!ELEMENT normal-spotlight-bullet-list (#PCDATA)><!ELEMENT normal-spotlight-first (#PCDATA)><!ELEMENT normal-table (#PCDATA)><!ELEMENT normal-table-right (#PCDATA)><!ELEMENT normal-testimonials (#PCDATA)><!ELEMENT normal-vff (#PCDATA)><!ELEMENT numbered-list (#PCDATA)><!ELEMENT numbered-list-restart (#PCDATA)><!ELEMENT numbered-sublist (#PCDATA)><!ELEMENT opening-quote-mark (#PCDATA)><!ELEMENT opening-quote-mark-yellow (#PCDATA)><!ELEMENT paragraph-style-2 (#PCDATA)><!ELEMENT pipe (#PCDATA)><!ELEMENT question (#PCDATA)><!ELEMENT question-first (#PCDATA)><!ELEMENT quote-insights (#PCDATA)><!ELEMENT quote-testimonials (#PCDATA)><!ELEMENT quote-vff (#PCDATA)><!ELEMENT recommendations ANY><!ELEMENT redana ANY><!ELEMENT regular (#PCDATA)><!ELEMENT regular-italic (#PCDATA)><!ELEMENT regular-no.-2-italic (#PCDATA)><!ELEMENT resources (#PCDATA)><!ELEMENT rest (#PCDATA)><!ELEMENT rh-bold (#PCDATA)><!ELEMENT rh-chapter-number (#PCDATA)><!ELEMENT rh-chapter-title (#PCDATA)><!ELEMENT rh-chpter-number-white (#PCDATA)><!ELEMENT rh-section-number (#PCDATA)><!ELEMENT right-col-cell (#PCDATA)><!ELEMENT right-col-cell-core (#PCDATA)><!ELEMENT right-col-cell-core-last (#PCDATA)><!ELEMENT right-col-core (#PCDATA)><!ELEMENT right-col-core-next (#PCDATA)><!ELEMENT running-header (#PCDATA)><!ELEMENT running-header-multi-line-1 (#PCDATA)><!ELEMENT running-header-multi-line-2 (#PCDATA)><!ELEMENT running-header-right (#PCDATA)><!ELEMENT running-header-white (#PCDATA)><!ELEMENT semantic ANY><!ELEMENT sidenotes-contribution-cbck ANY><!ELEMENT sidenotes-contribution-wbck ANY><!ELEMENT sidenotes-contribution-wbck-chap ANY><!ELEMENT sidenotes-contribution-wbck-chap-bottom ANY><!ELEMENT sidenotes-contributions (#PCDATA)><!ELEMENT sidenotes-contributions-2col (#PCDATA)><!ELEMENT sidenotes-contributions-first (#PCDATA)><!ELEMENT sidenotes-core (#PCDATA)><!ELEMENT sidenotes-foreword ANY><!ELEMENT sidenotes-matrix ANY><!ELEMENT small-quote (#PCDATA)><!ELEMENT small-quote-author (#PCDATA)><!ELEMENT source (#PCDATA)><!ELEMENT source-white (#PCDATA)><!ELEMENT subchapter-title (#PCDATA)><!ELEMENT subh-left (#PCDATA)><!ELEMENT subh-right (#PCDATA)><!ELEMENT subtitle (#PCDATA)><!ELEMENT subtitle-p9 (#PCDATA)><!ELEMENT subyears-right (#PCDATA)><!ELEMENT super-body-left (#PCDATA)><!ELEMENT super-body-right (#PCDATA)><!ELEMENT super-digit-left (#PCDATA)><!ELEMENT super-digit-right (#PCDATA)><!ELEMENT superscript (#PCDATA)><!ELEMENT t-header-left (#PCDATA)><!ELEMENT t-header-right (#PCDATA)><!ELEMENT t-normal-left (#PCDATA)><!ELEMENT t-normal-right (#PCDATA)><!ELEMENT t-subheader-left (#PCDATA)><!ELEMENT t-subheader-right (#PCDATA)><!ELEMENT t-superbody-left (#PCDATA)><!ELEMENT t-superbody-right (#PCDATA)><!ELEMENT t-superdigit-left (#PCDATA)><!ELEMENT table-anx (#PCDATA)><!ELEMENT table-fact ANY><!ELEMENT table-matrix ANY><!ELEMENT table-semantic ANY><!ELEMENT table-simple ANY><!ELEMENT tables-anx ANY><!ELEMENT tables-left (#PCDATA)><!ELEMENT tables-right (#PCDATA)><!ELEMENT thin-table (#PCDATA)><!ELEMENT tiktok-chapter-heading ANY><!ELEMENT title (#PCDATA)><!ELEMENT title-chapter ANY><!ELEMENT title-cover ANY><!ELEMENT title-p9 (#PCDATA)><!ELEMENT title-principles (#PCDATA)><!ELEMENT title-spine (#PCDATA)><!ELEMENT toh (#PCDATA)><!ELEMENT toh-cell (#PCDATA)><!ELEMENT toh-next (#PCDATA)><!ELEMENT txt-3c-anx ANY><!ELEMENT txt-body ANY><!ELEMENT txt-chapter-core ANY><!ELEMENT txt-chapter-img-core ANY><!ELEMENT txt-endnote ANY><!ELEMENT txt-guard-chapter ANY><!ELEMENT txt-guard-contribution ANY><!ELEMENT txt-principles ANY><!ELEMENT type-of-harm (#PCDATA)><!ELEMENT type-of-harm-2 (#PCDATA)><!ELEMENT unitensional (#PCDATA)><!ELEMENT website (#PCDATA)><!ELEMENT year (#PCDATA)>

=== Monash-Mosaic/IFRC_Report/scripts/wdr25/data/WDR26-Foreword-FR.with-links-and-endnotes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Story SYSTEM "/Users/ylfch/Dropbox/Innovation Team/Solferino Academy/Solferino Academy 2025 - DBX/WDR25/PROD/LAYOUT/FRENCH/02_EXPORTS/DTD/SYNTHESIS/04_FORE/wdr25_from_styles.dtd" [
]>
<Story>
    <fig href_fmt="images/v-LBN0443_fmt.png" href="file://images/v-LBN0443.png"></fig>
    <Story>
        <chapter-number>Avant-propos</chapter-number>
        <chapter-title>Par Jagan Chapagain </chapter-title>
        <chapter-subtitle>Secrétaire général, Fédération internationale des Sociétés de la
            Croix-Rouge et du Croissant-Rouge</chapter-subtitle>
        <normal>Dans toutes les crises dont j&#8217;ai été témoin &#8211; et dans toutes les
            interventions menées par le réseau international de la Croix-Rouge et du Croissant-Rouge
            en réponse à une catastrophe, à une urgence de santé publique, à un déplacement massif
            de population ou aux conséquences humanitaires d&#8217;un conflit armé &#8211;,
            l&#8217;information est aussi essentielle que la nourriture, l&#8217;eau et le logement.
            Elle guide les personnes vers la sécurité, les relie à leurs proches et leur donne les
            connaissances nécessaires pour se protéger et protéger <nonebreaking>leur </nonebreaking>
            communauté. </normal>
        <normal>Mais l&#8217;information peut aussi causer du tort. Lorsqu&#8217;elle est fausse,
            trompeuse ou délibérément manipulée, elle peut aggraver la peur, alimenter la
            discrimination, entraver l&#8217;accès humanitaire et coûter des vies. Nous
            l&#8217;avons trop souvent constaté : lors d&#8217;épidémies, quand les rumeurs prennent
            le pas sur les conseils sanitaires ; après des catastrophes, quand la méfiance entrave
            l&#8217;acheminement de l&#8217;aide ; et dans les conflits armés, quand les discours
            incendiaires exacerbent <nonebreaking>la </nonebreaking>violence. </normal>
        <normal>Les informations préjudiciables ne sont pas nouvelles, mais elles circulent
            aujourd&#8217;hui à une vitesse et à une échelle sans précédent. Les plateformes
            numériques ouvrent des canaux essentiels pour faire entendre la voix des communautés,
            mais elles constituent également un terrain fertile pour les mensonges. Dans cet
            environnement, la confiance <nonebreaking>est </nonebreaking>fragile. </normal>
        <normal>Dans les contextes humanitaires, les informations préjudiciables prospèrent là où la
            confiance est faible. La confiance influence fortement la propension des gens à croire,
            partager et diffuser des informations préjudiciables, ce qui détermine leur impact et
            leur portée. Les informations préjudiciables se nourrissent de la peur et de
            l&#8217;incertitude, affaiblissant les relations qui rendent possibles l&#8217;accès et
            l&#8217;action humanitaires. Sans confiance, les gens sont moins enclins à se préparer,
            à demander de l&#8217;aide ou à suivre des conseils qui peuvent leur sauver la vie.
            Lorsque la confiance existe, les communautés agissent ensemble, absorbent les chocs et
            se rétablissent plus efficacement. Maintenir la confiance n&#8217;est pas facultatif,
            c&#8217;est une <nonebreaking>nécessité </nonebreaking>humanitaire. </normal>
        <normal><regular-italic>Le Rapport sur les catastrophes dans le monde 2026 </regular-italic>appelle
            les gouvernements, les acteurs humanitaires, les médias, les entreprises technologiques
            et les communautés à reconnaître que la fiabilité de l&#8217;information est une
            question de vie ou de mort. Dans les situations d&#8217;urgence, tout comme nous
            planifions la logistique, les logements et les soins de santé, nous devons également
            planifier l&#8217;environnement informationnel. Cela nécessite d&#8217;investir dans
            l&#8217;engagement communautaire, de privilégier l&#8217;écoute plutôt que la parole, de
            renforcer la résilience face aux discours préjudiciables et de défendre systématiquement
            l&#8217;humanité, la neutralité, l&#8217;impartialité et l&#8217;indépendance dans
            chaque interaction et <nonebreaking>chaque </nonebreaking>message. </normal>
        <normal>En 2024, 32 volontaires et membres du personnel de la Croix-Rouge et du
            Croissant-Rouge ont été tués dans l&#8217;exercice de leurs fonctions ; en 2025, 27
            autres vies ont été perdues. Cela nous rappelle douloureusement les risques encourus par
            ceux qui font passer l&#8217;humanité avant tout, souvent dans les circonstances les
            plus dangereuses. Ces morts mettent en évidence la nécessité urgente de protéger le
            personnel humanitaire et les volontaires, et de préserver l&#8217;espace dont ils ont
            besoin pour sauver des vies. Tout ce qui aggrave la méfiance, alimente l&#8217;hostilité
            ou transforme l&#8217;emblème de la protection en cible doit être combattu de toute
            urgence. Si nous voulons honorer la mémoire de ceux qui ont perdu la vie, il nous faut
            faire face à cette crise avec diligence <nonebreaking>et </nonebreaking>détermination. </normal>
        <normal>L&#8217;espoir doit également faire partie de notre réponse. Les informations
            préjudiciables progressent dans la peur et la confusion, mais l&#8217;espoir, fondé sur
            la confiance, la solidarité et la dignité humaine, peut être tout aussi contagieux.
            Contrer les menaces par l&#8217;espoir et faire connaître les exemples d&#8217;action et
            les possibilités constitue un moyen d&#8217;opposition vital. Partout dans le monde, les
            communautés réagissent aux crises non seulement avec résilience, mais aussi avec
            créativité et compassion, ouvrant souvent la voie à des solutions. En diffusant les
            récits et les voix authentiques, nous faisons plus que contrer les fausses informations
            : nous encourageons l&#8217;action, nous renforçons la confiance et nous rappelons aux
            gens que même dans les moments les plus sombres, il existe des moyens d&#8217;aller <nonebreaking>
            de </nonebreaking>l&#8217;avant. </normal>
        <normal>La Fédération internationale et ses Sociétés nationales de la Croix-Rouge et du
            Croissant-Rouge membres ont toujours œuvré au cœur des communautés, dont elles ont gagné
            la confiance par leur présence, et par la transparence et le respect dont elles font
            preuve. Dans la crise de l&#8217;information que nous traversons aujourd&#8217;hui, ce
            rôle est plus important que jamais. Notre engagement est clair et inébranlable : agir
            avec humanité et sur la base de preuves, maintenir la confiance et placer les personnes
            en détresse au centre de notre action, afin que, dans les moments de peur et
            d&#8217;incertitude, les voix qui portent le plus loin soient celles qui guérissent,
            aident et protègent. Chacun d&#8217;entre nous a un rôle à jouer. En restant informés,
            en se posant des questions, en vérifiant et en diffusant uniquement ce qui est fiable et
            constructif, nous renforçons l&#8217;environnement informationnel et veillons à ce que
            l&#8217;espoir l&#8217;emporte sur la menace. </normal>
    </Story>
    <wdr-exported-hyperlinks>
    </wdr-exported-hyperlinks>
    <wdr-exported-endnote-hyperlinks>
    </wdr-exported-endnote-hyperlinks>
</Story>

=== Monash-Mosaic/IFRC_Report/scripts/wdr25/data/WDR26-Foreword-ZH.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Story SYSTEM "/Users/ylfch/Dropbox/Innovation Team/Solferino Academy/Solferino Academy 2025 - DBX/WDR25/PROD/LAYOUT/CHINESE/02_EXPORTS/DTD/04/wdr25_from_styles.dtd">
<Story>
  <Story>
    <chapter-number>前言 </chapter-number>
    <chapter-title>贾干·查普甘 </chapter-title>
    <chapter-subtitle>红十字会与红新月会国际联合会秘书长</chapter-subtitle>
    <normal>在我亲历的每场危机中——在国际红十字与红新月网络对灾害、公共卫生紧急事件、大规模人口流动或是武装冲突的人道主义后果启动的每一场响应中——信息都如同食物、水和住所般至关重要。信息指引人们走向安全，帮助他们与亲人取得联系，给予他们保护自身及社区的知识。 </normal>
    <normal>但信息也可能造成危害。当信息是虚假的、有误导性或被蓄意操纵时，就会加剧恐惧、助长歧视、阻碍人道援助准入，导致生命的代价。我们目睹过太多这样的场景：疾病暴发时，谣言的速度超过了医疗建议的传播；灾害发生后，不信任阻碍了赈济的配送；武装冲突中，煽动性的叙事使暴力升级。 </normal>
    <normal>有害信息并非新鲜事物，但如今其传播速度与覆盖范围已达到前所未有的水平。数字平台为社区发声开辟了重要渠道，却也为谎言提供了滋生的沃土。在这样的环境中，信任变得脆弱。 </normal>
    <normal>在人道主义情境中，信任薄弱之处往往滋生有害信息。信任深刻影响着人们是否相信、分享和扩散有害信息——有害信息的影响和传播范围就此形成。有害信息以恐惧和不确定性为滋养，削弱了维系人道准入和人道行动的纽带。缺乏信任时，人们更难做好危机准备、寻求援助或遵循救生指引；而信任存在时，社区便能协同行动，更有效地承受冲击并实现恢复。维护信任并非可有可无——这是人道主义的必要条件。 </normal>
    <normal>《2026年世界灾害报告》呼吁各国政府、人道行动方、媒体、科技公司及社区认识到：信息的可信度关乎生死存亡。正如我们在紧急状况中规划物流、住所和医疗服务，我们也必须为信息环境做规划。这需要投资于社区参与，优先倾听而非急于发言，建立抵御有害叙事的韧性，并在每一次互动和每一条信息中始终一贯地坚持人道、中立、公正和独立。 </normal>
    <normal>2024年，32名红十字与红新月志愿者及工作人员在执行任务时遇害；在2025年，又有27条生命逝去。这令人痛心地提醒着我们：那些将人道置于首位的人们，往往在最危险的环境中承担着巨大风险。他们的牺牲凸显出当务之急：必须保护人道工作人员和志愿者，保障他们开展救生行动所需的空间。任何加深不信任、助长敌意或将保护标志变成攻击目标的行为，都必须紧迫地直面处理。对逝者的缅怀，促使我们怀着紧迫感和决心来应对这场危机。 </normal>
    <normal>心怀希望也须成为我们应对的一部分。有害信息在恐惧与混乱中滋长，但植根于信任、团结与人类尊严的希望具有同样的感染力。在威胁与希望之间寻求平衡，培育主动性和可能性的叙事，能形成关键的制衡力量。世界各地的社区应对危机时，不仅展现出韧性，还展现出创造力和同理心，往往引领了解决方案的探索。通过放大真实的故事与声音，我们不仅能抵御虚假内容，更能激发行动、增强信任，并提醒人们：纵使身处至暗时刻，前路仍在。 </normal>
    <normal>红十字会与红新月会国际联合会及其红十字与红新月会成员始终扎根社区核心开展工作，以实际行动、透明度和尊重赢得信任。在当今的信息危机中，这一角色比以往任何时候都更为重要。我们的承诺清晰坚定：秉持人道，基于实证，捍卫信任，将有需求的人群置于首位——让恐惧与迷茫时刻，最能传遍四方的是那些治愈、援助与守护的声音。我们当中的每个人都肩负着责任。通过保持知情，提出质疑，积极核验，只扩散可信的建设性信息，我们能改善信息环境，让希望的声量盖过伤害<fig href_fmt="images/09_fmt.jpg" href="file:///Users/ylfch/Dropbox/Innovation%20Team/Solferino%20Academy/Solferino%20Academy%202025%20-%20DBX/WDR25/PROD/LAYOUT/ENGLISH/01_SOURCE/WDR26-EN-FULL-REPORT/Links/09.tif"/></normal>
  </Story>
</Story>

=== Monash-Mosaic/IFRC_Report/scripts/wdr25/data/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Root SYSTEM "wdr25_from_styles.dtd" [
]>
<Story>
  <fig
    href="MONOCHROME/CHAPTER-IMG-RED/v-LBN0525-bnew-big.tif"></fig>
  <Story>
    <normal>The task now is to ensure that the necessary safeguards, engagement, proximity, trust
      and resilience are not left to chance or profit, but are deliberately harnessed to protect
      people and enable principled humanitarian action.<fig
        href="DUOTONES/P-CMR381-AB.tif"></fig>
    </normal>
    <normal>Trust is critical to the legitimacy, effectiveness and acceptance of humanitarian
      action. This was strongly emphasized at the 2019 International Conference of the Red Cross and
      Red Crescent Movement which recognized<regular-italic> </regular-italic>that trust in
      principled humanitarian action is indispensable to serving at-risk people and encouraged all
      members of the conference to act to preserve and develop this trust.<endnotes-ref>[^]</endnotes-ref>
      Crucially, trust in humanitarian action does not rest solely on humanitarian actors. It also
      depends on a conducive environment &#8211; one in which principled, effective and accountable
      action is actively supported. Such an environment is shaped by the legal, political and
      operational frameworks established by states and other actors. This includes respect for
      humanitarian principles, flexible and needs-based funding, protection of humanitarian access
      and clear delineation of roles and responsibilities of various actors. </normal>
  </Story>
  <fig
    href="DUOTONES/p-CMR481-AB.jpg"></fig>
</Story>
